name: "test_maze_ppo"
function_name: "train_rl_agent"
time_stamp_name: False
wandb_project: "rl_generalisation"

function_kwargs:
  env_kwargs:
    id: "Maze-v0"
    size: 8
    # observation_mode: "image"
  
  get_agent_kwargs:
    algorithm: "PPO"
    create_agent_kwargs:
      policy: "MlpPolicy"  # "CnnPolicy"
      learning_rate: 0.0001
      n_steps: 256
      batch_size: 64
      n_epochs: 10
      gamma: 0.95
      gae_lambda: 0.9
      clip_range: 0.2
      ent_coef: 0.01
      vf_coef: 0.5
      max_grad_norm: 0.5

  agent_train_kwargs:
    total_timesteps: 100_000
    log_interval: 100
  
  checkpoint_freq: 25_000
  checkpoint_dir: "testing/checkpoints/RUN_NAME"

  eval_policy_kwargs:
    should_wait_for_user: True
    visualise_episodes: 3
    log_rewards: True
