name: "visualise_maze_checkpoint"
function_name: "eval_agent"

function_kwargs:
  env_kwargs:
    id: "Maze-v0"
    size: 5
    observation_mode: "image"
  
  get_agent_kwargs:
    checkpoint_path: "testing/checkpoints/test_maze_ppo_pixels/rl_model_750000_steps.zip"
    algorithm: "PPO"
  
  eval_policy_kwargs:
    visualise_episodes: 5
    log_rewards: True
    max_steps_per_episode: 50
